#############################################################################
# Makefile for building: Simulation_of_the_4th_Krakow_bypass
# Generated by qmake (3.1) (Qt 5.9.6)
# Project:  Simulation_of_the_4th_Krakow_bypass.pro
# Template: app
# Command: /home/mazi/anaconda3/bin/qmake -o Makefile Simulation_of_the_4th_Krakow_bypass.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I. -I../anaconda3/include/qt -I../anaconda3/include/qt/QtWidgets -I../anaconda3/include/qt/QtGui -I../anaconda3/include/qt/QtCore -I. -I../anaconda3/mkspecs/linux-g++
QMAKE         = /home/mazi/anaconda3/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /home/mazi/anaconda3/bin/qmake -install qinstall
QINSTALL_PROGRAM = /home/mazi/anaconda3/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Simulation_of_the_4th_Krakow_bypass1.0.0
DISTDIR = /home/mazi/Simulation_of_the_4th_Krakow_bypass/.tmp/Simulation_of_the_4th_Krakow_bypass1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/home/mazi/anaconda3/lib
LIBS          = $(SUBLIBS) -L/home/mazi/anaconda3/lib -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = bypass/Bypass.cpp \
		bypass/BypassSection.cpp \
		bypass/Car.cpp \
		bypass/Junction.cpp \
		bypass/Road.cpp \
		bypass/Simulation.cpp \
		Bypass_GUI/car_graphic.cpp \
		Bypass_GUI/main.cpp \
		Bypass_GUI/simulation_gui.cpp \
		bypass/vehicle.cpp qrc_res.cpp \
		moc_car_graphic.cpp \
		moc_simulation_gui.cpp \
		moc_Vehicle.cpp
OBJECTS       = Bypass.o \
		BypassSection.o \
		Car.o \
		Junction.o \
		Road.o \
		Simulation.o \
		car_graphic.o \
		main.o \
		simulation_gui.o \
		vehicle.o \
		qrc_res.o \
		moc_car_graphic.o \
		moc_simulation_gui.o \
		moc_Vehicle.o
DIST          = ../anaconda3/mkspecs/features/spec_pre.prf \
		../anaconda3/mkspecs/common/unix.conf \
		../anaconda3/mkspecs/common/linux.conf \
		../anaconda3/mkspecs/common/sanitize.conf \
		../anaconda3/mkspecs/common/gcc-base.conf \
		../anaconda3/mkspecs/common/gcc-base-unix.conf \
		../anaconda3/mkspecs/common/g++-base.conf \
		../anaconda3/mkspecs/common/g++-unix.conf \
		../anaconda3/mkspecs/qconfig.pri \
		../anaconda3/mkspecs/modules/qt_lib_3danimation.pri \
		../anaconda3/mkspecs/modules/qt_lib_3danimation_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_3dcore.pri \
		../anaconda3/mkspecs/modules/qt_lib_3dcore_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_3dextras.pri \
		../anaconda3/mkspecs/modules/qt_lib_3dextras_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_3dinput.pri \
		../anaconda3/mkspecs/modules/qt_lib_3dinput_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_3dlogic.pri \
		../anaconda3/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_3dquick.pri \
		../anaconda3/mkspecs/modules/qt_lib_3dquick_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../anaconda3/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_3dquickextras.pri \
		../anaconda3/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_3dquickinput.pri \
		../anaconda3/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_3dquickrender.pri \
		../anaconda3/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../anaconda3/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_3drender.pri \
		../anaconda3/mkspecs/modules/qt_lib_3drender_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_bluetooth.pri \
		../anaconda3/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_charts.pri \
		../anaconda3/mkspecs/modules/qt_lib_charts_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_concurrent.pri \
		../anaconda3/mkspecs/modules/qt_lib_concurrent_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_core.pri \
		../anaconda3/mkspecs/modules/qt_lib_core_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_datavisualization.pri \
		../anaconda3/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_dbus.pri \
		../anaconda3/mkspecs/modules/qt_lib_dbus_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_designer.pri \
		../anaconda3/mkspecs/modules/qt_lib_designer_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_egl_support_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_fb_support_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_gamepad.pri \
		../anaconda3/mkspecs/modules/qt_lib_gamepad_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_glx_support_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_gui.pri \
		../anaconda3/mkspecs/modules/qt_lib_gui_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_help.pri \
		../anaconda3/mkspecs/modules/qt_lib_help_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_input_support_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_location.pri \
		../anaconda3/mkspecs/modules/qt_lib_location_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_multimedia.pri \
		../anaconda3/mkspecs/modules/qt_lib_multimedia_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../anaconda3/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_network.pri \
		../anaconda3/mkspecs/modules/qt_lib_network_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_networkauth.pri \
		../anaconda3/mkspecs/modules/qt_lib_networkauth_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_nfc.pri \
		../anaconda3/mkspecs/modules/qt_lib_nfc_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_opengl.pri \
		../anaconda3/mkspecs/modules/qt_lib_opengl_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_openglextensions.pri \
		../anaconda3/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_positioning.pri \
		../anaconda3/mkspecs/modules/qt_lib_positioning_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_printsupport.pri \
		../anaconda3/mkspecs/modules/qt_lib_printsupport_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_purchasing.pri \
		../anaconda3/mkspecs/modules/qt_lib_purchasing_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_qml.pri \
		../anaconda3/mkspecs/modules/qt_lib_qml_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_qmltest.pri \
		../anaconda3/mkspecs/modules/qt_lib_qmltest_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_quick.pri \
		../anaconda3/mkspecs/modules/qt_lib_quick_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../anaconda3/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_quickwidgets.pri \
		../anaconda3/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_remoteobjects.pri \
		../anaconda3/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_repparser.pri \
		../anaconda3/mkspecs/modules/qt_lib_repparser_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_script.pri \
		../anaconda3/mkspecs/modules/qt_lib_script_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_scripttools.pri \
		../anaconda3/mkspecs/modules/qt_lib_scripttools_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_scxml.pri \
		../anaconda3/mkspecs/modules/qt_lib_scxml_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_sensors.pri \
		../anaconda3/mkspecs/modules/qt_lib_sensors_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_serialbus.pri \
		../anaconda3/mkspecs/modules/qt_lib_serialbus_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_serialport.pri \
		../anaconda3/mkspecs/modules/qt_lib_serialport_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_service_support_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_sql.pri \
		../anaconda3/mkspecs/modules/qt_lib_sql_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_svg.pri \
		../anaconda3/mkspecs/modules/qt_lib_svg_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_testlib.pri \
		../anaconda3/mkspecs/modules/qt_lib_testlib_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_texttospeech.pri \
		../anaconda3/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_theme_support_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_uiplugin.pri \
		../anaconda3/mkspecs/modules/qt_lib_uitools.pri \
		../anaconda3/mkspecs/modules/qt_lib_uitools_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_webchannel.pri \
		../anaconda3/mkspecs/modules/qt_lib_webchannel_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_webengine.pri \
		../anaconda3/mkspecs/modules/qt_lib_webengine_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_webenginecore.pri \
		../anaconda3/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../anaconda3/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_websockets.pri \
		../anaconda3/mkspecs/modules/qt_lib_websockets_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_webview.pri \
		../anaconda3/mkspecs/modules/qt_lib_webview_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_widgets.pri \
		../anaconda3/mkspecs/modules/qt_lib_widgets_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_x11extras.pri \
		../anaconda3/mkspecs/modules/qt_lib_x11extras_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_xml.pri \
		../anaconda3/mkspecs/modules/qt_lib_xml_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../anaconda3/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../anaconda3/mkspecs/features/qt_functions.prf \
		../anaconda3/mkspecs/features/qt_config.prf \
		../anaconda3/mkspecs/linux-g++/qmake.conf \
		../anaconda3/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../anaconda3/mkspecs/features/exclusive_builds.prf \
		../anaconda3/mkspecs/features/toolchain.prf \
		../anaconda3/mkspecs/features/default_pre.prf \
		../anaconda3/mkspecs/features/resolve_config.prf \
		../anaconda3/mkspecs/features/default_post.prf \
		../anaconda3/mkspecs/features/warn_on.prf \
		../anaconda3/mkspecs/features/qt.prf \
		../anaconda3/mkspecs/features/resources.prf \
		../anaconda3/mkspecs/features/moc.prf \
		../anaconda3/mkspecs/features/unix/opengl.prf \
		../anaconda3/mkspecs/features/uic.prf \
		../anaconda3/mkspecs/features/unix/thread.prf \
		../anaconda3/mkspecs/features/qmake_use.prf \
		../anaconda3/mkspecs/features/file_copies.prf \
		../anaconda3/mkspecs/features/testcase_targets.prf \
		../anaconda3/mkspecs/features/exceptions.prf \
		../anaconda3/mkspecs/features/yacc.prf \
		../anaconda3/mkspecs/features/lex.prf \
		Simulation_of_the_4th_Krakow_bypass.pro bypass/Bypass.hpp \
		Bypass_GUI/car_graphic.hpp \
		Bypass_GUI/simulation_gui.hpp \
		bypass/BypassSection.hpp \
		bypass/Car.hpp \
		bypass/Junction.hpp \
		bypass/Road.hpp \
		bypass/Simulation.hpp \
		bypass/Vehicle.hpp bypass/Bypass.cpp \
		bypass/BypassSection.cpp \
		bypass/Car.cpp \
		bypass/Junction.cpp \
		bypass/Road.cpp \
		bypass/Simulation.cpp \
		Bypass_GUI/car_graphic.cpp \
		Bypass_GUI/main.cpp \
		Bypass_GUI/simulation_gui.cpp \
		bypass/vehicle.cpp
QMAKE_TARGET  = Simulation_of_the_4th_Krakow_bypass
DESTDIR       = 
TARGET        = Simulation_of_the_4th_Krakow_bypass


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Simulation_of_the_4th_Krakow_bypass.pro ../anaconda3/mkspecs/linux-g++/qmake.conf ../anaconda3/mkspecs/features/spec_pre.prf \
		../anaconda3/mkspecs/common/unix.conf \
		../anaconda3/mkspecs/common/linux.conf \
		../anaconda3/mkspecs/common/sanitize.conf \
		../anaconda3/mkspecs/common/gcc-base.conf \
		../anaconda3/mkspecs/common/gcc-base-unix.conf \
		../anaconda3/mkspecs/common/g++-base.conf \
		../anaconda3/mkspecs/common/g++-unix.conf \
		../anaconda3/mkspecs/qconfig.pri \
		../anaconda3/mkspecs/modules/qt_lib_3danimation.pri \
		../anaconda3/mkspecs/modules/qt_lib_3danimation_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_3dcore.pri \
		../anaconda3/mkspecs/modules/qt_lib_3dcore_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_3dextras.pri \
		../anaconda3/mkspecs/modules/qt_lib_3dextras_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_3dinput.pri \
		../anaconda3/mkspecs/modules/qt_lib_3dinput_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_3dlogic.pri \
		../anaconda3/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_3dquick.pri \
		../anaconda3/mkspecs/modules/qt_lib_3dquick_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../anaconda3/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_3dquickextras.pri \
		../anaconda3/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_3dquickinput.pri \
		../anaconda3/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_3dquickrender.pri \
		../anaconda3/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../anaconda3/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_3drender.pri \
		../anaconda3/mkspecs/modules/qt_lib_3drender_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_bluetooth.pri \
		../anaconda3/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_charts.pri \
		../anaconda3/mkspecs/modules/qt_lib_charts_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_concurrent.pri \
		../anaconda3/mkspecs/modules/qt_lib_concurrent_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_core.pri \
		../anaconda3/mkspecs/modules/qt_lib_core_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_datavisualization.pri \
		../anaconda3/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_dbus.pri \
		../anaconda3/mkspecs/modules/qt_lib_dbus_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_designer.pri \
		../anaconda3/mkspecs/modules/qt_lib_designer_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_egl_support_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_fb_support_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_gamepad.pri \
		../anaconda3/mkspecs/modules/qt_lib_gamepad_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_glx_support_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_gui.pri \
		../anaconda3/mkspecs/modules/qt_lib_gui_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_help.pri \
		../anaconda3/mkspecs/modules/qt_lib_help_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_input_support_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_location.pri \
		../anaconda3/mkspecs/modules/qt_lib_location_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_multimedia.pri \
		../anaconda3/mkspecs/modules/qt_lib_multimedia_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../anaconda3/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_network.pri \
		../anaconda3/mkspecs/modules/qt_lib_network_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_networkauth.pri \
		../anaconda3/mkspecs/modules/qt_lib_networkauth_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_nfc.pri \
		../anaconda3/mkspecs/modules/qt_lib_nfc_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_opengl.pri \
		../anaconda3/mkspecs/modules/qt_lib_opengl_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_openglextensions.pri \
		../anaconda3/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_positioning.pri \
		../anaconda3/mkspecs/modules/qt_lib_positioning_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_printsupport.pri \
		../anaconda3/mkspecs/modules/qt_lib_printsupport_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_purchasing.pri \
		../anaconda3/mkspecs/modules/qt_lib_purchasing_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_qml.pri \
		../anaconda3/mkspecs/modules/qt_lib_qml_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_qmltest.pri \
		../anaconda3/mkspecs/modules/qt_lib_qmltest_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_quick.pri \
		../anaconda3/mkspecs/modules/qt_lib_quick_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../anaconda3/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_quickwidgets.pri \
		../anaconda3/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_remoteobjects.pri \
		../anaconda3/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_repparser.pri \
		../anaconda3/mkspecs/modules/qt_lib_repparser_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_script.pri \
		../anaconda3/mkspecs/modules/qt_lib_script_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_scripttools.pri \
		../anaconda3/mkspecs/modules/qt_lib_scripttools_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_scxml.pri \
		../anaconda3/mkspecs/modules/qt_lib_scxml_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_sensors.pri \
		../anaconda3/mkspecs/modules/qt_lib_sensors_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_serialbus.pri \
		../anaconda3/mkspecs/modules/qt_lib_serialbus_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_serialport.pri \
		../anaconda3/mkspecs/modules/qt_lib_serialport_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_service_support_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_sql.pri \
		../anaconda3/mkspecs/modules/qt_lib_sql_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_svg.pri \
		../anaconda3/mkspecs/modules/qt_lib_svg_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_testlib.pri \
		../anaconda3/mkspecs/modules/qt_lib_testlib_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_texttospeech.pri \
		../anaconda3/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_theme_support_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_uiplugin.pri \
		../anaconda3/mkspecs/modules/qt_lib_uitools.pri \
		../anaconda3/mkspecs/modules/qt_lib_uitools_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_webchannel.pri \
		../anaconda3/mkspecs/modules/qt_lib_webchannel_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_webengine.pri \
		../anaconda3/mkspecs/modules/qt_lib_webengine_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_webenginecore.pri \
		../anaconda3/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../anaconda3/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_websockets.pri \
		../anaconda3/mkspecs/modules/qt_lib_websockets_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_webview.pri \
		../anaconda3/mkspecs/modules/qt_lib_webview_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_widgets.pri \
		../anaconda3/mkspecs/modules/qt_lib_widgets_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_x11extras.pri \
		../anaconda3/mkspecs/modules/qt_lib_x11extras_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_xml.pri \
		../anaconda3/mkspecs/modules/qt_lib_xml_private.pri \
		../anaconda3/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../anaconda3/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../anaconda3/mkspecs/features/qt_functions.prf \
		../anaconda3/mkspecs/features/qt_config.prf \
		../anaconda3/mkspecs/linux-g++/qmake.conf \
		../anaconda3/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../anaconda3/mkspecs/features/exclusive_builds.prf \
		../anaconda3/mkspecs/features/toolchain.prf \
		../anaconda3/mkspecs/features/default_pre.prf \
		../anaconda3/mkspecs/features/resolve_config.prf \
		../anaconda3/mkspecs/features/default_post.prf \
		../anaconda3/mkspecs/features/warn_on.prf \
		../anaconda3/mkspecs/features/qt.prf \
		../anaconda3/mkspecs/features/resources.prf \
		../anaconda3/mkspecs/features/moc.prf \
		../anaconda3/mkspecs/features/unix/opengl.prf \
		../anaconda3/mkspecs/features/uic.prf \
		../anaconda3/mkspecs/features/unix/thread.prf \
		../anaconda3/mkspecs/features/qmake_use.prf \
		../anaconda3/mkspecs/features/file_copies.prf \
		../anaconda3/mkspecs/features/testcase_targets.prf \
		../anaconda3/mkspecs/features/exceptions.prf \
		../anaconda3/mkspecs/features/yacc.prf \
		../anaconda3/mkspecs/features/lex.prf \
		Simulation_of_the_4th_Krakow_bypass.pro \
		Bypass_GUI/res.qrc \
		../anaconda3/lib/libQt5Widgets.prl \
		../anaconda3/lib/libQt5Gui.prl \
		../anaconda3/lib/libQt5Core.prl
	$(QMAKE) -o Makefile Simulation_of_the_4th_Krakow_bypass.pro
../anaconda3/mkspecs/features/spec_pre.prf:
../anaconda3/mkspecs/common/unix.conf:
../anaconda3/mkspecs/common/linux.conf:
../anaconda3/mkspecs/common/sanitize.conf:
../anaconda3/mkspecs/common/gcc-base.conf:
../anaconda3/mkspecs/common/gcc-base-unix.conf:
../anaconda3/mkspecs/common/g++-base.conf:
../anaconda3/mkspecs/common/g++-unix.conf:
../anaconda3/mkspecs/qconfig.pri:
../anaconda3/mkspecs/modules/qt_lib_3danimation.pri:
../anaconda3/mkspecs/modules/qt_lib_3danimation_private.pri:
../anaconda3/mkspecs/modules/qt_lib_3dcore.pri:
../anaconda3/mkspecs/modules/qt_lib_3dcore_private.pri:
../anaconda3/mkspecs/modules/qt_lib_3dextras.pri:
../anaconda3/mkspecs/modules/qt_lib_3dextras_private.pri:
../anaconda3/mkspecs/modules/qt_lib_3dinput.pri:
../anaconda3/mkspecs/modules/qt_lib_3dinput_private.pri:
../anaconda3/mkspecs/modules/qt_lib_3dlogic.pri:
../anaconda3/mkspecs/modules/qt_lib_3dlogic_private.pri:
../anaconda3/mkspecs/modules/qt_lib_3dquick.pri:
../anaconda3/mkspecs/modules/qt_lib_3dquick_private.pri:
../anaconda3/mkspecs/modules/qt_lib_3dquickanimation.pri:
../anaconda3/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../anaconda3/mkspecs/modules/qt_lib_3dquickextras.pri:
../anaconda3/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../anaconda3/mkspecs/modules/qt_lib_3dquickinput.pri:
../anaconda3/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../anaconda3/mkspecs/modules/qt_lib_3dquickrender.pri:
../anaconda3/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../anaconda3/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../anaconda3/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../anaconda3/mkspecs/modules/qt_lib_3drender.pri:
../anaconda3/mkspecs/modules/qt_lib_3drender_private.pri:
../anaconda3/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../anaconda3/mkspecs/modules/qt_lib_bluetooth.pri:
../anaconda3/mkspecs/modules/qt_lib_bluetooth_private.pri:
../anaconda3/mkspecs/modules/qt_lib_bootstrap_private.pri:
../anaconda3/mkspecs/modules/qt_lib_charts.pri:
../anaconda3/mkspecs/modules/qt_lib_charts_private.pri:
../anaconda3/mkspecs/modules/qt_lib_concurrent.pri:
../anaconda3/mkspecs/modules/qt_lib_concurrent_private.pri:
../anaconda3/mkspecs/modules/qt_lib_core.pri:
../anaconda3/mkspecs/modules/qt_lib_core_private.pri:
../anaconda3/mkspecs/modules/qt_lib_datavisualization.pri:
../anaconda3/mkspecs/modules/qt_lib_datavisualization_private.pri:
../anaconda3/mkspecs/modules/qt_lib_dbus.pri:
../anaconda3/mkspecs/modules/qt_lib_dbus_private.pri:
../anaconda3/mkspecs/modules/qt_lib_designer.pri:
../anaconda3/mkspecs/modules/qt_lib_designer_private.pri:
../anaconda3/mkspecs/modules/qt_lib_designercomponents_private.pri:
../anaconda3/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../anaconda3/mkspecs/modules/qt_lib_egl_support_private.pri:
../anaconda3/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
../anaconda3/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../anaconda3/mkspecs/modules/qt_lib_fb_support_private.pri:
../anaconda3/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../anaconda3/mkspecs/modules/qt_lib_gamepad.pri:
../anaconda3/mkspecs/modules/qt_lib_gamepad_private.pri:
../anaconda3/mkspecs/modules/qt_lib_glx_support_private.pri:
../anaconda3/mkspecs/modules/qt_lib_gui.pri:
../anaconda3/mkspecs/modules/qt_lib_gui_private.pri:
../anaconda3/mkspecs/modules/qt_lib_help.pri:
../anaconda3/mkspecs/modules/qt_lib_help_private.pri:
../anaconda3/mkspecs/modules/qt_lib_input_support_private.pri:
../anaconda3/mkspecs/modules/qt_lib_location.pri:
../anaconda3/mkspecs/modules/qt_lib_location_private.pri:
../anaconda3/mkspecs/modules/qt_lib_multimedia.pri:
../anaconda3/mkspecs/modules/qt_lib_multimedia_private.pri:
../anaconda3/mkspecs/modules/qt_lib_multimediawidgets.pri:
../anaconda3/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../anaconda3/mkspecs/modules/qt_lib_network.pri:
../anaconda3/mkspecs/modules/qt_lib_network_private.pri:
../anaconda3/mkspecs/modules/qt_lib_networkauth.pri:
../anaconda3/mkspecs/modules/qt_lib_networkauth_private.pri:
../anaconda3/mkspecs/modules/qt_lib_nfc.pri:
../anaconda3/mkspecs/modules/qt_lib_nfc_private.pri:
../anaconda3/mkspecs/modules/qt_lib_opengl.pri:
../anaconda3/mkspecs/modules/qt_lib_opengl_private.pri:
../anaconda3/mkspecs/modules/qt_lib_openglextensions.pri:
../anaconda3/mkspecs/modules/qt_lib_openglextensions_private.pri:
../anaconda3/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../anaconda3/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../anaconda3/mkspecs/modules/qt_lib_positioning.pri:
../anaconda3/mkspecs/modules/qt_lib_positioning_private.pri:
../anaconda3/mkspecs/modules/qt_lib_printsupport.pri:
../anaconda3/mkspecs/modules/qt_lib_printsupport_private.pri:
../anaconda3/mkspecs/modules/qt_lib_purchasing.pri:
../anaconda3/mkspecs/modules/qt_lib_purchasing_private.pri:
../anaconda3/mkspecs/modules/qt_lib_qml.pri:
../anaconda3/mkspecs/modules/qt_lib_qml_private.pri:
../anaconda3/mkspecs/modules/qt_lib_qmldebug_private.pri:
../anaconda3/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../anaconda3/mkspecs/modules/qt_lib_qmltest.pri:
../anaconda3/mkspecs/modules/qt_lib_qmltest_private.pri:
../anaconda3/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../anaconda3/mkspecs/modules/qt_lib_quick.pri:
../anaconda3/mkspecs/modules/qt_lib_quick_private.pri:
../anaconda3/mkspecs/modules/qt_lib_quickcontrols2.pri:
../anaconda3/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../anaconda3/mkspecs/modules/qt_lib_quickparticles_private.pri:
../anaconda3/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../anaconda3/mkspecs/modules/qt_lib_quickwidgets.pri:
../anaconda3/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../anaconda3/mkspecs/modules/qt_lib_remoteobjects.pri:
../anaconda3/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../anaconda3/mkspecs/modules/qt_lib_repparser.pri:
../anaconda3/mkspecs/modules/qt_lib_repparser_private.pri:
../anaconda3/mkspecs/modules/qt_lib_script.pri:
../anaconda3/mkspecs/modules/qt_lib_script_private.pri:
../anaconda3/mkspecs/modules/qt_lib_scripttools.pri:
../anaconda3/mkspecs/modules/qt_lib_scripttools_private.pri:
../anaconda3/mkspecs/modules/qt_lib_scxml.pri:
../anaconda3/mkspecs/modules/qt_lib_scxml_private.pri:
../anaconda3/mkspecs/modules/qt_lib_sensors.pri:
../anaconda3/mkspecs/modules/qt_lib_sensors_private.pri:
../anaconda3/mkspecs/modules/qt_lib_serialbus.pri:
../anaconda3/mkspecs/modules/qt_lib_serialbus_private.pri:
../anaconda3/mkspecs/modules/qt_lib_serialport.pri:
../anaconda3/mkspecs/modules/qt_lib_serialport_private.pri:
../anaconda3/mkspecs/modules/qt_lib_service_support_private.pri:
../anaconda3/mkspecs/modules/qt_lib_sql.pri:
../anaconda3/mkspecs/modules/qt_lib_sql_private.pri:
../anaconda3/mkspecs/modules/qt_lib_svg.pri:
../anaconda3/mkspecs/modules/qt_lib_svg_private.pri:
../anaconda3/mkspecs/modules/qt_lib_testlib.pri:
../anaconda3/mkspecs/modules/qt_lib_testlib_private.pri:
../anaconda3/mkspecs/modules/qt_lib_texttospeech.pri:
../anaconda3/mkspecs/modules/qt_lib_texttospeech_private.pri:
../anaconda3/mkspecs/modules/qt_lib_theme_support_private.pri:
../anaconda3/mkspecs/modules/qt_lib_uiplugin.pri:
../anaconda3/mkspecs/modules/qt_lib_uitools.pri:
../anaconda3/mkspecs/modules/qt_lib_uitools_private.pri:
../anaconda3/mkspecs/modules/qt_lib_webchannel.pri:
../anaconda3/mkspecs/modules/qt_lib_webchannel_private.pri:
../anaconda3/mkspecs/modules/qt_lib_webengine.pri:
../anaconda3/mkspecs/modules/qt_lib_webengine_private.pri:
../anaconda3/mkspecs/modules/qt_lib_webenginecore.pri:
../anaconda3/mkspecs/modules/qt_lib_webenginecore_private.pri:
../anaconda3/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../anaconda3/mkspecs/modules/qt_lib_webenginewidgets.pri:
../anaconda3/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../anaconda3/mkspecs/modules/qt_lib_websockets.pri:
../anaconda3/mkspecs/modules/qt_lib_websockets_private.pri:
../anaconda3/mkspecs/modules/qt_lib_webview.pri:
../anaconda3/mkspecs/modules/qt_lib_webview_private.pri:
../anaconda3/mkspecs/modules/qt_lib_widgets.pri:
../anaconda3/mkspecs/modules/qt_lib_widgets_private.pri:
../anaconda3/mkspecs/modules/qt_lib_x11extras.pri:
../anaconda3/mkspecs/modules/qt_lib_x11extras_private.pri:
../anaconda3/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
../anaconda3/mkspecs/modules/qt_lib_xml.pri:
../anaconda3/mkspecs/modules/qt_lib_xml_private.pri:
../anaconda3/mkspecs/modules/qt_lib_xmlpatterns.pri:
../anaconda3/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../anaconda3/mkspecs/features/qt_functions.prf:
../anaconda3/mkspecs/features/qt_config.prf:
../anaconda3/mkspecs/linux-g++/qmake.conf:
../anaconda3/mkspecs/features/spec_post.prf:
.qmake.stash:
../anaconda3/mkspecs/features/exclusive_builds.prf:
../anaconda3/mkspecs/features/toolchain.prf:
../anaconda3/mkspecs/features/default_pre.prf:
../anaconda3/mkspecs/features/resolve_config.prf:
../anaconda3/mkspecs/features/default_post.prf:
../anaconda3/mkspecs/features/warn_on.prf:
../anaconda3/mkspecs/features/qt.prf:
../anaconda3/mkspecs/features/resources.prf:
../anaconda3/mkspecs/features/moc.prf:
../anaconda3/mkspecs/features/unix/opengl.prf:
../anaconda3/mkspecs/features/uic.prf:
../anaconda3/mkspecs/features/unix/thread.prf:
../anaconda3/mkspecs/features/qmake_use.prf:
../anaconda3/mkspecs/features/file_copies.prf:
../anaconda3/mkspecs/features/testcase_targets.prf:
../anaconda3/mkspecs/features/exceptions.prf:
../anaconda3/mkspecs/features/yacc.prf:
../anaconda3/mkspecs/features/lex.prf:
Simulation_of_the_4th_Krakow_bypass.pro:
Bypass_GUI/res.qrc:
../anaconda3/lib/libQt5Widgets.prl:
../anaconda3/lib/libQt5Gui.prl:
../anaconda3/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile Simulation_of_the_4th_Krakow_bypass.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents Bypass_GUI/res.qrc $(DISTDIR)/
	$(COPY_FILE) --parents ../anaconda3/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents bypass/Bypass.hpp Bypass_GUI/car_graphic.hpp Bypass_GUI/simulation_gui.hpp bypass/BypassSection.hpp bypass/Car.hpp bypass/Junction.hpp bypass/Road.hpp bypass/Simulation.hpp bypass/Vehicle.hpp $(DISTDIR)/
	$(COPY_FILE) --parents bypass/Bypass.cpp bypass/BypassSection.cpp bypass/Car.cpp bypass/Junction.cpp bypass/Road.cpp bypass/Simulation.cpp Bypass_GUI/car_graphic.cpp Bypass_GUI/main.cpp Bypass_GUI/simulation_gui.cpp bypass/vehicle.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_res.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_res.cpp
qrc_res.cpp: Bypass_GUI/res.qrc \
		../anaconda3/bin/rcc \
		Bypass_GUI/Part9.png \
		Bypass_GUI/Part12.png \
		Bypass_GUI/Part4.png \
		Bypass_GUI/Part8.png \
		Bypass_GUI/Part11.png \
		Bypass_GUI/Part3.png \
		Bypass_GUI/Part7.png \
		Bypass_GUI/highway.png \
		Bypass_GUI/Part10.png \
		Bypass_GUI/car.png \
		Bypass_GUI/Part2.png \
		Bypass_GUI/car2.png \
		Bypass_GUI/Part6.png \
		Bypass_GUI/map.png \
		Bypass_GUI/Part13.png \
		Bypass_GUI/Part1.png \
		Bypass_GUI/Part5.png
	/home/mazi/anaconda3/bin/rcc -name res Bypass_GUI/res.qrc -o qrc_res.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../anaconda3/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -std=gnu++11 -Wall -W -dM -E -o moc_predefs.h ../anaconda3/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_car_graphic.cpp moc_simulation_gui.cpp moc_Vehicle.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_car_graphic.cpp moc_simulation_gui.cpp moc_Vehicle.cpp
moc_car_graphic.cpp: ../anaconda3/include/qt/QtWidgets/QGraphicsPixmapItem \
		../anaconda3/include/qt/QtWidgets/qgraphicsitem.h \
		../anaconda3/include/qt/QtWidgets/qtwidgetsglobal.h \
		../anaconda3/include/qt/QtGui/qtguiglobal.h \
		../anaconda3/include/qt/QtCore/qglobal.h \
		../anaconda3/include/qt/QtCore/qconfig-bootstrapped.h \
		../anaconda3/include/qt/QtCore/qconfig.h \
		../anaconda3/include/qt/QtCore/qtcore-config.h \
		../anaconda3/include/qt/QtCore/qsystemdetection.h \
		../anaconda3/include/qt/QtCore/qprocessordetection.h \
		../anaconda3/include/qt/QtCore/qcompilerdetection.h \
		../anaconda3/include/qt/QtCore/qtypeinfo.h \
		../anaconda3/include/qt/QtCore/qsysinfo.h \
		../anaconda3/include/qt/QtCore/qlogging.h \
		../anaconda3/include/qt/QtCore/qflags.h \
		../anaconda3/include/qt/QtCore/qatomic.h \
		../anaconda3/include/qt/QtCore/qbasicatomic.h \
		../anaconda3/include/qt/QtCore/qatomic_bootstrap.h \
		../anaconda3/include/qt/QtCore/qgenericatomic.h \
		../anaconda3/include/qt/QtCore/qatomic_cxx11.h \
		../anaconda3/include/qt/QtCore/qatomic_msvc.h \
		../anaconda3/include/qt/QtCore/qglobalstatic.h \
		../anaconda3/include/qt/QtCore/qmutex.h \
		../anaconda3/include/qt/QtCore/qnumeric.h \
		../anaconda3/include/qt/QtCore/qversiontagging.h \
		../anaconda3/include/qt/QtGui/qtgui-config.h \
		../anaconda3/include/qt/QtWidgets/qtwidgets-config.h \
		../anaconda3/include/qt/QtCore/qobject.h \
		../anaconda3/include/qt/QtCore/qobjectdefs.h \
		../anaconda3/include/qt/QtCore/qnamespace.h \
		../anaconda3/include/qt/QtCore/qobjectdefs_impl.h \
		../anaconda3/include/qt/QtCore/qstring.h \
		../anaconda3/include/qt/QtCore/qchar.h \
		../anaconda3/include/qt/QtCore/qbytearray.h \
		../anaconda3/include/qt/QtCore/qrefcount.h \
		../anaconda3/include/qt/QtCore/qarraydata.h \
		../anaconda3/include/qt/QtCore/qstringbuilder.h \
		../anaconda3/include/qt/QtCore/qlist.h \
		../anaconda3/include/qt/QtCore/qalgorithms.h \
		../anaconda3/include/qt/QtCore/qiterator.h \
		../anaconda3/include/qt/QtCore/qhashfunctions.h \
		../anaconda3/include/qt/QtCore/qpair.h \
		../anaconda3/include/qt/QtCore/qbytearraylist.h \
		../anaconda3/include/qt/QtCore/qstringlist.h \
		../anaconda3/include/qt/QtCore/qregexp.h \
		../anaconda3/include/qt/QtCore/qstringmatcher.h \
		../anaconda3/include/qt/QtCore/qcoreevent.h \
		../anaconda3/include/qt/QtCore/qscopedpointer.h \
		../anaconda3/include/qt/QtCore/qmetatype.h \
		../anaconda3/include/qt/QtCore/qvarlengtharray.h \
		../anaconda3/include/qt/QtCore/qcontainerfwd.h \
		../anaconda3/include/qt/QtCore/qobject_impl.h \
		../anaconda3/include/qt/QtCore/qvariant.h \
		../anaconda3/include/qt/QtCore/qmap.h \
		../anaconda3/include/qt/QtCore/qdebug.h \
		../anaconda3/include/qt/QtCore/qhash.h \
		../anaconda3/include/qt/QtCore/qtextstream.h \
		../anaconda3/include/qt/QtCore/qiodevice.h \
		../anaconda3/include/qt/QtCore/qlocale.h \
		../anaconda3/include/qt/QtCore/qshareddata.h \
		../anaconda3/include/qt/QtCore/qvector.h \
		../anaconda3/include/qt/QtCore/qpoint.h \
		../anaconda3/include/qt/QtCore/qset.h \
		../anaconda3/include/qt/QtCore/qcontiguouscache.h \
		../anaconda3/include/qt/QtCore/qsharedpointer.h \
		../anaconda3/include/qt/QtCore/qsharedpointer_impl.h \
		../anaconda3/include/qt/QtCore/qrect.h \
		../anaconda3/include/qt/QtCore/qmargins.h \
		../anaconda3/include/qt/QtCore/qsize.h \
		../anaconda3/include/qt/QtGui/qpainterpath.h \
		../anaconda3/include/qt/QtGui/qmatrix.h \
		../anaconda3/include/qt/QtGui/qpolygon.h \
		../anaconda3/include/qt/QtGui/qregion.h \
		../anaconda3/include/qt/QtGui/qwindowdefs.h \
		../anaconda3/include/qt/QtGui/qwindowdefs_win.h \
		../anaconda3/include/qt/QtCore/qdatastream.h \
		../anaconda3/include/qt/QtCore/qline.h \
		../anaconda3/include/qt/QtGui/qpixmap.h \
		../anaconda3/include/qt/QtGui/qpaintdevice.h \
		../anaconda3/include/qt/QtGui/qcolor.h \
		../anaconda3/include/qt/QtGui/qrgb.h \
		../anaconda3/include/qt/QtGui/qrgba64.h \
		../anaconda3/include/qt/QtGui/qimage.h \
		../anaconda3/include/qt/QtGui/qpixelformat.h \
		../anaconda3/include/qt/QtGui/qtransform.h \
		../anaconda3/include/qt/QtWidgets/QGraphicsItem \
		../anaconda3/include/qt/QtCore/QObject \
		Bypass_GUI/car_graphic.hpp \
		moc_predefs.h \
		../anaconda3/bin/moc
	/home/mazi/anaconda3/bin/moc $(DEFINES) --include ./moc_predefs.h -I/home/mazi/anaconda3/mkspecs/linux-g++ -I/home/mazi/Simulation_of_the_4th_Krakow_bypass -I/home/mazi/Simulation_of_the_4th_Krakow_bypass -I/home/mazi/anaconda3/include/qt -I/home/mazi/anaconda3/include/qt/QtWidgets -I/home/mazi/anaconda3/include/qt/QtGui -I/home/mazi/anaconda3/include/qt/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Bypass_GUI/car_graphic.hpp -o moc_car_graphic.cpp

moc_simulation_gui.cpp: ../anaconda3/include/qt/QtWidgets/QGraphicsView \
		../anaconda3/include/qt/QtWidgets/qgraphicsview.h \
		../anaconda3/include/qt/QtWidgets/qtwidgetsglobal.h \
		../anaconda3/include/qt/QtGui/qtguiglobal.h \
		../anaconda3/include/qt/QtCore/qglobal.h \
		../anaconda3/include/qt/QtCore/qconfig-bootstrapped.h \
		../anaconda3/include/qt/QtCore/qconfig.h \
		../anaconda3/include/qt/QtCore/qtcore-config.h \
		../anaconda3/include/qt/QtCore/qsystemdetection.h \
		../anaconda3/include/qt/QtCore/qprocessordetection.h \
		../anaconda3/include/qt/QtCore/qcompilerdetection.h \
		../anaconda3/include/qt/QtCore/qtypeinfo.h \
		../anaconda3/include/qt/QtCore/qsysinfo.h \
		../anaconda3/include/qt/QtCore/qlogging.h \
		../anaconda3/include/qt/QtCore/qflags.h \
		../anaconda3/include/qt/QtCore/qatomic.h \
		../anaconda3/include/qt/QtCore/qbasicatomic.h \
		../anaconda3/include/qt/QtCore/qatomic_bootstrap.h \
		../anaconda3/include/qt/QtCore/qgenericatomic.h \
		../anaconda3/include/qt/QtCore/qatomic_cxx11.h \
		../anaconda3/include/qt/QtCore/qatomic_msvc.h \
		../anaconda3/include/qt/QtCore/qglobalstatic.h \
		../anaconda3/include/qt/QtCore/qmutex.h \
		../anaconda3/include/qt/QtCore/qnumeric.h \
		../anaconda3/include/qt/QtCore/qversiontagging.h \
		../anaconda3/include/qt/QtGui/qtgui-config.h \
		../anaconda3/include/qt/QtWidgets/qtwidgets-config.h \
		../anaconda3/include/qt/QtCore/qmetatype.h \
		../anaconda3/include/qt/QtCore/qbytearray.h \
		../anaconda3/include/qt/QtCore/qrefcount.h \
		../anaconda3/include/qt/QtCore/qnamespace.h \
		../anaconda3/include/qt/QtCore/qarraydata.h \
		../anaconda3/include/qt/QtCore/qstring.h \
		../anaconda3/include/qt/QtCore/qchar.h \
		../anaconda3/include/qt/QtCore/qstringbuilder.h \
		../anaconda3/include/qt/QtCore/qvarlengtharray.h \
		../anaconda3/include/qt/QtCore/qcontainerfwd.h \
		../anaconda3/include/qt/QtCore/qalgorithms.h \
		../anaconda3/include/qt/QtCore/qobjectdefs.h \
		../anaconda3/include/qt/QtCore/qobjectdefs_impl.h \
		../anaconda3/include/qt/QtGui/qpainter.h \
		../anaconda3/include/qt/QtCore/qrect.h \
		../anaconda3/include/qt/QtCore/qmargins.h \
		../anaconda3/include/qt/QtCore/qsize.h \
		../anaconda3/include/qt/QtCore/qpoint.h \
		../anaconda3/include/qt/QtCore/qscopedpointer.h \
		../anaconda3/include/qt/QtGui/qpixmap.h \
		../anaconda3/include/qt/QtGui/qpaintdevice.h \
		../anaconda3/include/qt/QtGui/qwindowdefs.h \
		../anaconda3/include/qt/QtGui/qwindowdefs_win.h \
		../anaconda3/include/qt/QtGui/qcolor.h \
		../anaconda3/include/qt/QtGui/qrgb.h \
		../anaconda3/include/qt/QtCore/qstringlist.h \
		../anaconda3/include/qt/QtCore/qlist.h \
		../anaconda3/include/qt/QtCore/qiterator.h \
		../anaconda3/include/qt/QtCore/qhashfunctions.h \
		../anaconda3/include/qt/QtCore/qpair.h \
		../anaconda3/include/qt/QtCore/qbytearraylist.h \
		../anaconda3/include/qt/QtCore/qregexp.h \
		../anaconda3/include/qt/QtCore/qstringmatcher.h \
		../anaconda3/include/qt/QtGui/qrgba64.h \
		../anaconda3/include/qt/QtCore/qsharedpointer.h \
		../anaconda3/include/qt/QtCore/qshareddata.h \
		../anaconda3/include/qt/QtCore/qhash.h \
		../anaconda3/include/qt/QtCore/qsharedpointer_impl.h \
		../anaconda3/include/qt/QtCore/qobject.h \
		../anaconda3/include/qt/QtCore/qcoreevent.h \
		../anaconda3/include/qt/QtCore/qobject_impl.h \
		../anaconda3/include/qt/QtGui/qimage.h \
		../anaconda3/include/qt/QtGui/qpixelformat.h \
		../anaconda3/include/qt/QtGui/qtransform.h \
		../anaconda3/include/qt/QtGui/qmatrix.h \
		../anaconda3/include/qt/QtGui/qpolygon.h \
		../anaconda3/include/qt/QtCore/qvector.h \
		../anaconda3/include/qt/QtGui/qregion.h \
		../anaconda3/include/qt/QtCore/qdatastream.h \
		../anaconda3/include/qt/QtCore/qiodevice.h \
		../anaconda3/include/qt/QtCore/qline.h \
		../anaconda3/include/qt/QtGui/qpainterpath.h \
		../anaconda3/include/qt/QtGui/qtextoption.h \
		../anaconda3/include/qt/QtGui/qpen.h \
		../anaconda3/include/qt/QtGui/qbrush.h \
		../anaconda3/include/qt/QtGui/qfontinfo.h \
		../anaconda3/include/qt/QtGui/qfont.h \
		../anaconda3/include/qt/QtGui/qfontmetrics.h \
		../anaconda3/include/qt/QtWidgets/qscrollarea.h \
		../anaconda3/include/qt/QtWidgets/qabstractscrollarea.h \
		../anaconda3/include/qt/QtWidgets/qframe.h \
		../anaconda3/include/qt/QtWidgets/qwidget.h \
		../anaconda3/include/qt/QtGui/qpalette.h \
		../anaconda3/include/qt/QtWidgets/qsizepolicy.h \
		../anaconda3/include/qt/QtGui/qcursor.h \
		../anaconda3/include/qt/QtGui/qkeysequence.h \
		../anaconda3/include/qt/QtGui/qevent.h \
		../anaconda3/include/qt/QtCore/qvariant.h \
		../anaconda3/include/qt/QtCore/qmap.h \
		../anaconda3/include/qt/QtCore/qdebug.h \
		../anaconda3/include/qt/QtCore/qtextstream.h \
		../anaconda3/include/qt/QtCore/qlocale.h \
		../anaconda3/include/qt/QtCore/qset.h \
		../anaconda3/include/qt/QtCore/qcontiguouscache.h \
		../anaconda3/include/qt/QtCore/qurl.h \
		../anaconda3/include/qt/QtCore/qurlquery.h \
		../anaconda3/include/qt/QtCore/qfile.h \
		../anaconda3/include/qt/QtCore/qfiledevice.h \
		../anaconda3/include/qt/QtGui/qvector2d.h \
		../anaconda3/include/qt/QtGui/qtouchdevice.h \
		../anaconda3/include/qt/QtWidgets/qgraphicsscene.h \
		../anaconda3/include/qt/QtWidgets/QGraphicsPixmapItem \
		../anaconda3/include/qt/QtWidgets/qgraphicsitem.h \
		../anaconda3/include/qt/QtWidgets/QGraphicsItem \
		../anaconda3/include/qt/QtCore/QObject \
		../anaconda3/include/qt/QtWidgets/QGraphicsScene \
		../anaconda3/include/qt/QtWidgets/QPushButton \
		../anaconda3/include/qt/QtWidgets/qpushbutton.h \
		../anaconda3/include/qt/QtWidgets/qabstractbutton.h \
		../anaconda3/include/qt/QtGui/qicon.h \
		../anaconda3/include/qt/QtWidgets/QGridLayout \
		../anaconda3/include/qt/QtWidgets/qgridlayout.h \
		../anaconda3/include/qt/QtWidgets/qlayout.h \
		../anaconda3/include/qt/QtWidgets/qlayoutitem.h \
		../anaconda3/include/qt/QtWidgets/qboxlayout.h \
		../anaconda3/include/qt/QtWidgets/QTextEdit \
		../anaconda3/include/qt/QtWidgets/qtextedit.h \
		../anaconda3/include/qt/QtGui/qtextdocument.h \
		../anaconda3/include/qt/QtGui/qtextcursor.h \
		../anaconda3/include/qt/QtGui/qtextformat.h \
		../anaconda3/include/qt/QtWidgets/QSlider \
		../anaconda3/include/qt/QtWidgets/qslider.h \
		../anaconda3/include/qt/QtWidgets/qabstractslider.h \
		Bypass_GUI/car_graphic.hpp \
		bypass/Simulation.hpp \
		bypass/Bypass.hpp \
		bypass/BypassSection.hpp \
		bypass/Vehicle.hpp \
		bypass/Road.hpp \
		bypass/Junction.hpp \
		../anaconda3/include/qt/QtCore/QTimer \
		../anaconda3/include/qt/QtCore/qtimer.h \
		../anaconda3/include/qt/QtCore/qbasictimer.h \
		Bypass_GUI/simulation_gui.hpp \
		moc_predefs.h \
		../anaconda3/bin/moc
	/home/mazi/anaconda3/bin/moc $(DEFINES) --include ./moc_predefs.h -I/home/mazi/anaconda3/mkspecs/linux-g++ -I/home/mazi/Simulation_of_the_4th_Krakow_bypass -I/home/mazi/Simulation_of_the_4th_Krakow_bypass -I/home/mazi/anaconda3/include/qt -I/home/mazi/anaconda3/include/qt/QtWidgets -I/home/mazi/anaconda3/include/qt/QtGui -I/home/mazi/anaconda3/include/qt/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Bypass_GUI/simulation_gui.hpp -o moc_simulation_gui.cpp

moc_Vehicle.cpp: ../anaconda3/include/qt/QtWidgets/QGraphicsPixmapItem \
		../anaconda3/include/qt/QtWidgets/qgraphicsitem.h \
		../anaconda3/include/qt/QtWidgets/qtwidgetsglobal.h \
		../anaconda3/include/qt/QtGui/qtguiglobal.h \
		../anaconda3/include/qt/QtCore/qglobal.h \
		../anaconda3/include/qt/QtCore/qconfig-bootstrapped.h \
		../anaconda3/include/qt/QtCore/qconfig.h \
		../anaconda3/include/qt/QtCore/qtcore-config.h \
		../anaconda3/include/qt/QtCore/qsystemdetection.h \
		../anaconda3/include/qt/QtCore/qprocessordetection.h \
		../anaconda3/include/qt/QtCore/qcompilerdetection.h \
		../anaconda3/include/qt/QtCore/qtypeinfo.h \
		../anaconda3/include/qt/QtCore/qsysinfo.h \
		../anaconda3/include/qt/QtCore/qlogging.h \
		../anaconda3/include/qt/QtCore/qflags.h \
		../anaconda3/include/qt/QtCore/qatomic.h \
		../anaconda3/include/qt/QtCore/qbasicatomic.h \
		../anaconda3/include/qt/QtCore/qatomic_bootstrap.h \
		../anaconda3/include/qt/QtCore/qgenericatomic.h \
		../anaconda3/include/qt/QtCore/qatomic_cxx11.h \
		../anaconda3/include/qt/QtCore/qatomic_msvc.h \
		../anaconda3/include/qt/QtCore/qglobalstatic.h \
		../anaconda3/include/qt/QtCore/qmutex.h \
		../anaconda3/include/qt/QtCore/qnumeric.h \
		../anaconda3/include/qt/QtCore/qversiontagging.h \
		../anaconda3/include/qt/QtGui/qtgui-config.h \
		../anaconda3/include/qt/QtWidgets/qtwidgets-config.h \
		../anaconda3/include/qt/QtCore/qobject.h \
		../anaconda3/include/qt/QtCore/qobjectdefs.h \
		../anaconda3/include/qt/QtCore/qnamespace.h \
		../anaconda3/include/qt/QtCore/qobjectdefs_impl.h \
		../anaconda3/include/qt/QtCore/qstring.h \
		../anaconda3/include/qt/QtCore/qchar.h \
		../anaconda3/include/qt/QtCore/qbytearray.h \
		../anaconda3/include/qt/QtCore/qrefcount.h \
		../anaconda3/include/qt/QtCore/qarraydata.h \
		../anaconda3/include/qt/QtCore/qstringbuilder.h \
		../anaconda3/include/qt/QtCore/qlist.h \
		../anaconda3/include/qt/QtCore/qalgorithms.h \
		../anaconda3/include/qt/QtCore/qiterator.h \
		../anaconda3/include/qt/QtCore/qhashfunctions.h \
		../anaconda3/include/qt/QtCore/qpair.h \
		../anaconda3/include/qt/QtCore/qbytearraylist.h \
		../anaconda3/include/qt/QtCore/qstringlist.h \
		../anaconda3/include/qt/QtCore/qregexp.h \
		../anaconda3/include/qt/QtCore/qstringmatcher.h \
		../anaconda3/include/qt/QtCore/qcoreevent.h \
		../anaconda3/include/qt/QtCore/qscopedpointer.h \
		../anaconda3/include/qt/QtCore/qmetatype.h \
		../anaconda3/include/qt/QtCore/qvarlengtharray.h \
		../anaconda3/include/qt/QtCore/qcontainerfwd.h \
		../anaconda3/include/qt/QtCore/qobject_impl.h \
		../anaconda3/include/qt/QtCore/qvariant.h \
		../anaconda3/include/qt/QtCore/qmap.h \
		../anaconda3/include/qt/QtCore/qdebug.h \
		../anaconda3/include/qt/QtCore/qhash.h \
		../anaconda3/include/qt/QtCore/qtextstream.h \
		../anaconda3/include/qt/QtCore/qiodevice.h \
		../anaconda3/include/qt/QtCore/qlocale.h \
		../anaconda3/include/qt/QtCore/qshareddata.h \
		../anaconda3/include/qt/QtCore/qvector.h \
		../anaconda3/include/qt/QtCore/qpoint.h \
		../anaconda3/include/qt/QtCore/qset.h \
		../anaconda3/include/qt/QtCore/qcontiguouscache.h \
		../anaconda3/include/qt/QtCore/qsharedpointer.h \
		../anaconda3/include/qt/QtCore/qsharedpointer_impl.h \
		../anaconda3/include/qt/QtCore/qrect.h \
		../anaconda3/include/qt/QtCore/qmargins.h \
		../anaconda3/include/qt/QtCore/qsize.h \
		../anaconda3/include/qt/QtGui/qpainterpath.h \
		../anaconda3/include/qt/QtGui/qmatrix.h \
		../anaconda3/include/qt/QtGui/qpolygon.h \
		../anaconda3/include/qt/QtGui/qregion.h \
		../anaconda3/include/qt/QtGui/qwindowdefs.h \
		../anaconda3/include/qt/QtGui/qwindowdefs_win.h \
		../anaconda3/include/qt/QtCore/qdatastream.h \
		../anaconda3/include/qt/QtCore/qline.h \
		../anaconda3/include/qt/QtGui/qpixmap.h \
		../anaconda3/include/qt/QtGui/qpaintdevice.h \
		../anaconda3/include/qt/QtGui/qcolor.h \
		../anaconda3/include/qt/QtGui/qrgb.h \
		../anaconda3/include/qt/QtGui/qrgba64.h \
		../anaconda3/include/qt/QtGui/qimage.h \
		../anaconda3/include/qt/QtGui/qpixelformat.h \
		../anaconda3/include/qt/QtGui/qtransform.h \
		../anaconda3/include/qt/QtWidgets/QGraphicsItem \
		../anaconda3/include/qt/QtCore/QObject \
		bypass/Vehicle.hpp \
		moc_predefs.h \
		../anaconda3/bin/moc
	/home/mazi/anaconda3/bin/moc $(DEFINES) --include ./moc_predefs.h -I/home/mazi/anaconda3/mkspecs/linux-g++ -I/home/mazi/Simulation_of_the_4th_Krakow_bypass -I/home/mazi/Simulation_of_the_4th_Krakow_bypass -I/home/mazi/anaconda3/include/qt -I/home/mazi/anaconda3/include/qt/QtWidgets -I/home/mazi/anaconda3/include/qt/QtGui -I/home/mazi/anaconda3/include/qt/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include bypass/Vehicle.hpp -o moc_Vehicle.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

Bypass.o: bypass/Bypass.cpp bypass/Bypass.hpp \
		bypass/BypassSection.hpp \
		bypass/Road.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Bypass.o bypass/Bypass.cpp

BypassSection.o: bypass/BypassSection.cpp bypass/BypassSection.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BypassSection.o bypass/BypassSection.cpp

Car.o: bypass/Car.cpp bypass/Car.hpp \
		bypass/Vehicle.hpp \
		../anaconda3/include/qt/QtWidgets/QGraphicsPixmapItem \
		../anaconda3/include/qt/QtWidgets/qgraphicsitem.h \
		../anaconda3/include/qt/QtWidgets/qtwidgetsglobal.h \
		../anaconda3/include/qt/QtGui/qtguiglobal.h \
		../anaconda3/include/qt/QtCore/qglobal.h \
		../anaconda3/include/qt/QtCore/qconfig-bootstrapped.h \
		../anaconda3/include/qt/QtCore/qconfig.h \
		../anaconda3/include/qt/QtCore/qtcore-config.h \
		../anaconda3/include/qt/QtCore/qsystemdetection.h \
		../anaconda3/include/qt/QtCore/qprocessordetection.h \
		../anaconda3/include/qt/QtCore/qcompilerdetection.h \
		../anaconda3/include/qt/QtCore/qtypeinfo.h \
		../anaconda3/include/qt/QtCore/qsysinfo.h \
		../anaconda3/include/qt/QtCore/qlogging.h \
		../anaconda3/include/qt/QtCore/qflags.h \
		../anaconda3/include/qt/QtCore/qatomic.h \
		../anaconda3/include/qt/QtCore/qbasicatomic.h \
		../anaconda3/include/qt/QtCore/qatomic_bootstrap.h \
		../anaconda3/include/qt/QtCore/qgenericatomic.h \
		../anaconda3/include/qt/QtCore/qatomic_cxx11.h \
		../anaconda3/include/qt/QtCore/qatomic_msvc.h \
		../anaconda3/include/qt/QtCore/qglobalstatic.h \
		../anaconda3/include/qt/QtCore/qmutex.h \
		../anaconda3/include/qt/QtCore/qnumeric.h \
		../anaconda3/include/qt/QtCore/qversiontagging.h \
		../anaconda3/include/qt/QtGui/qtgui-config.h \
		../anaconda3/include/qt/QtWidgets/qtwidgets-config.h \
		../anaconda3/include/qt/QtCore/qobject.h \
		../anaconda3/include/qt/QtCore/qobjectdefs.h \
		../anaconda3/include/qt/QtCore/qnamespace.h \
		../anaconda3/include/qt/QtCore/qobjectdefs_impl.h \
		../anaconda3/include/qt/QtCore/qstring.h \
		../anaconda3/include/qt/QtCore/qchar.h \
		../anaconda3/include/qt/QtCore/qbytearray.h \
		../anaconda3/include/qt/QtCore/qrefcount.h \
		../anaconda3/include/qt/QtCore/qarraydata.h \
		../anaconda3/include/qt/QtCore/qstringbuilder.h \
		../anaconda3/include/qt/QtCore/qlist.h \
		../anaconda3/include/qt/QtCore/qalgorithms.h \
		../anaconda3/include/qt/QtCore/qiterator.h \
		../anaconda3/include/qt/QtCore/qhashfunctions.h \
		../anaconda3/include/qt/QtCore/qpair.h \
		../anaconda3/include/qt/QtCore/qbytearraylist.h \
		../anaconda3/include/qt/QtCore/qstringlist.h \
		../anaconda3/include/qt/QtCore/qregexp.h \
		../anaconda3/include/qt/QtCore/qstringmatcher.h \
		../anaconda3/include/qt/QtCore/qcoreevent.h \
		../anaconda3/include/qt/QtCore/qscopedpointer.h \
		../anaconda3/include/qt/QtCore/qmetatype.h \
		../anaconda3/include/qt/QtCore/qvarlengtharray.h \
		../anaconda3/include/qt/QtCore/qcontainerfwd.h \
		../anaconda3/include/qt/QtCore/qobject_impl.h \
		../anaconda3/include/qt/QtCore/qvariant.h \
		../anaconda3/include/qt/QtCore/qmap.h \
		../anaconda3/include/qt/QtCore/qdebug.h \
		../anaconda3/include/qt/QtCore/qhash.h \
		../anaconda3/include/qt/QtCore/qtextstream.h \
		../anaconda3/include/qt/QtCore/qiodevice.h \
		../anaconda3/include/qt/QtCore/qlocale.h \
		../anaconda3/include/qt/QtCore/qshareddata.h \
		../anaconda3/include/qt/QtCore/qvector.h \
		../anaconda3/include/qt/QtCore/qpoint.h \
		../anaconda3/include/qt/QtCore/qset.h \
		../anaconda3/include/qt/QtCore/qcontiguouscache.h \
		../anaconda3/include/qt/QtCore/qsharedpointer.h \
		../anaconda3/include/qt/QtCore/qsharedpointer_impl.h \
		../anaconda3/include/qt/QtCore/qrect.h \
		../anaconda3/include/qt/QtCore/qmargins.h \
		../anaconda3/include/qt/QtCore/qsize.h \
		../anaconda3/include/qt/QtGui/qpainterpath.h \
		../anaconda3/include/qt/QtGui/qmatrix.h \
		../anaconda3/include/qt/QtGui/qpolygon.h \
		../anaconda3/include/qt/QtGui/qregion.h \
		../anaconda3/include/qt/QtGui/qwindowdefs.h \
		../anaconda3/include/qt/QtGui/qwindowdefs_win.h \
		../anaconda3/include/qt/QtCore/qdatastream.h \
		../anaconda3/include/qt/QtCore/qline.h \
		../anaconda3/include/qt/QtGui/qpixmap.h \
		../anaconda3/include/qt/QtGui/qpaintdevice.h \
		../anaconda3/include/qt/QtGui/qcolor.h \
		../anaconda3/include/qt/QtGui/qrgb.h \
		../anaconda3/include/qt/QtGui/qrgba64.h \
		../anaconda3/include/qt/QtGui/qimage.h \
		../anaconda3/include/qt/QtGui/qpixelformat.h \
		../anaconda3/include/qt/QtGui/qtransform.h \
		../anaconda3/include/qt/QtWidgets/QGraphicsItem \
		../anaconda3/include/qt/QtCore/QObject
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Car.o bypass/Car.cpp

Junction.o: bypass/Junction.cpp bypass/Junction.hpp \
		bypass/BypassSection.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Junction.o bypass/Junction.cpp

Road.o: bypass/Road.cpp bypass/Road.hpp \
		bypass/BypassSection.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Road.o bypass/Road.cpp

Simulation.o: bypass/Simulation.cpp bypass/Simulation.hpp \
		../anaconda3/include/qt/QtWidgets/QGraphicsScene \
		../anaconda3/include/qt/QtWidgets/qgraphicsscene.h \
		../anaconda3/include/qt/QtWidgets/qtwidgetsglobal.h \
		../anaconda3/include/qt/QtGui/qtguiglobal.h \
		../anaconda3/include/qt/QtCore/qglobal.h \
		../anaconda3/include/qt/QtCore/qconfig-bootstrapped.h \
		../anaconda3/include/qt/QtCore/qconfig.h \
		../anaconda3/include/qt/QtCore/qtcore-config.h \
		../anaconda3/include/qt/QtCore/qsystemdetection.h \
		../anaconda3/include/qt/QtCore/qprocessordetection.h \
		../anaconda3/include/qt/QtCore/qcompilerdetection.h \
		../anaconda3/include/qt/QtCore/qtypeinfo.h \
		../anaconda3/include/qt/QtCore/qsysinfo.h \
		../anaconda3/include/qt/QtCore/qlogging.h \
		../anaconda3/include/qt/QtCore/qflags.h \
		../anaconda3/include/qt/QtCore/qatomic.h \
		../anaconda3/include/qt/QtCore/qbasicatomic.h \
		../anaconda3/include/qt/QtCore/qatomic_bootstrap.h \
		../anaconda3/include/qt/QtCore/qgenericatomic.h \
		../anaconda3/include/qt/QtCore/qatomic_cxx11.h \
		../anaconda3/include/qt/QtCore/qatomic_msvc.h \
		../anaconda3/include/qt/QtCore/qglobalstatic.h \
		../anaconda3/include/qt/QtCore/qmutex.h \
		../anaconda3/include/qt/QtCore/qnumeric.h \
		../anaconda3/include/qt/QtCore/qversiontagging.h \
		../anaconda3/include/qt/QtGui/qtgui-config.h \
		../anaconda3/include/qt/QtWidgets/qtwidgets-config.h \
		../anaconda3/include/qt/QtCore/qobject.h \
		../anaconda3/include/qt/QtCore/qobjectdefs.h \
		../anaconda3/include/qt/QtCore/qnamespace.h \
		../anaconda3/include/qt/QtCore/qobjectdefs_impl.h \
		../anaconda3/include/qt/QtCore/qstring.h \
		../anaconda3/include/qt/QtCore/qchar.h \
		../anaconda3/include/qt/QtCore/qbytearray.h \
		../anaconda3/include/qt/QtCore/qrefcount.h \
		../anaconda3/include/qt/QtCore/qarraydata.h \
		../anaconda3/include/qt/QtCore/qstringbuilder.h \
		../anaconda3/include/qt/QtCore/qlist.h \
		../anaconda3/include/qt/QtCore/qalgorithms.h \
		../anaconda3/include/qt/QtCore/qiterator.h \
		../anaconda3/include/qt/QtCore/qhashfunctions.h \
		../anaconda3/include/qt/QtCore/qpair.h \
		../anaconda3/include/qt/QtCore/qbytearraylist.h \
		../anaconda3/include/qt/QtCore/qstringlist.h \
		../anaconda3/include/qt/QtCore/qregexp.h \
		../anaconda3/include/qt/QtCore/qstringmatcher.h \
		../anaconda3/include/qt/QtCore/qcoreevent.h \
		../anaconda3/include/qt/QtCore/qscopedpointer.h \
		../anaconda3/include/qt/QtCore/qmetatype.h \
		../anaconda3/include/qt/QtCore/qvarlengtharray.h \
		../anaconda3/include/qt/QtCore/qcontainerfwd.h \
		../anaconda3/include/qt/QtCore/qobject_impl.h \
		../anaconda3/include/qt/QtCore/qpoint.h \
		../anaconda3/include/qt/QtCore/qrect.h \
		../anaconda3/include/qt/QtCore/qmargins.h \
		../anaconda3/include/qt/QtCore/qsize.h \
		../anaconda3/include/qt/QtGui/qbrush.h \
		../anaconda3/include/qt/QtCore/qvector.h \
		../anaconda3/include/qt/QtGui/qcolor.h \
		../anaconda3/include/qt/QtGui/qrgb.h \
		../anaconda3/include/qt/QtGui/qrgba64.h \
		../anaconda3/include/qt/QtGui/qmatrix.h \
		../anaconda3/include/qt/QtGui/qpolygon.h \
		../anaconda3/include/qt/QtGui/qregion.h \
		../anaconda3/include/qt/QtGui/qwindowdefs.h \
		../anaconda3/include/qt/QtGui/qwindowdefs_win.h \
		../anaconda3/include/qt/QtCore/qdatastream.h \
		../anaconda3/include/qt/QtCore/qiodevice.h \
		../anaconda3/include/qt/QtCore/qline.h \
		../anaconda3/include/qt/QtGui/qtransform.h \
		../anaconda3/include/qt/QtGui/qpainterpath.h \
		../anaconda3/include/qt/QtGui/qimage.h \
		../anaconda3/include/qt/QtGui/qpaintdevice.h \
		../anaconda3/include/qt/QtGui/qpixelformat.h \
		../anaconda3/include/qt/QtGui/qpixmap.h \
		../anaconda3/include/qt/QtCore/qsharedpointer.h \
		../anaconda3/include/qt/QtCore/qshareddata.h \
		../anaconda3/include/qt/QtCore/qhash.h \
		../anaconda3/include/qt/QtCore/qsharedpointer_impl.h \
		../anaconda3/include/qt/QtGui/qfont.h \
		../anaconda3/include/qt/QtGui/qpen.h \
		bypass/Bypass.hpp \
		bypass/BypassSection.hpp \
		bypass/Vehicle.hpp \
		../anaconda3/include/qt/QtWidgets/QGraphicsPixmapItem \
		../anaconda3/include/qt/QtWidgets/qgraphicsitem.h \
		../anaconda3/include/qt/QtCore/qvariant.h \
		../anaconda3/include/qt/QtCore/qmap.h \
		../anaconda3/include/qt/QtCore/qdebug.h \
		../anaconda3/include/qt/QtCore/qtextstream.h \
		../anaconda3/include/qt/QtCore/qlocale.h \
		../anaconda3/include/qt/QtCore/qset.h \
		../anaconda3/include/qt/QtCore/qcontiguouscache.h \
		../anaconda3/include/qt/QtWidgets/QGraphicsItem \
		../anaconda3/include/qt/QtCore/QObject \
		bypass/Road.hpp \
		bypass/Junction.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Simulation.o bypass/Simulation.cpp

car_graphic.o: Bypass_GUI/car_graphic.cpp Bypass_GUI/car_graphic.hpp \
		../anaconda3/include/qt/QtWidgets/QGraphicsPixmapItem \
		../anaconda3/include/qt/QtWidgets/qgraphicsitem.h \
		../anaconda3/include/qt/QtWidgets/qtwidgetsglobal.h \
		../anaconda3/include/qt/QtGui/qtguiglobal.h \
		../anaconda3/include/qt/QtCore/qglobal.h \
		../anaconda3/include/qt/QtCore/qconfig-bootstrapped.h \
		../anaconda3/include/qt/QtCore/qconfig.h \
		../anaconda3/include/qt/QtCore/qtcore-config.h \
		../anaconda3/include/qt/QtCore/qsystemdetection.h \
		../anaconda3/include/qt/QtCore/qprocessordetection.h \
		../anaconda3/include/qt/QtCore/qcompilerdetection.h \
		../anaconda3/include/qt/QtCore/qtypeinfo.h \
		../anaconda3/include/qt/QtCore/qsysinfo.h \
		../anaconda3/include/qt/QtCore/qlogging.h \
		../anaconda3/include/qt/QtCore/qflags.h \
		../anaconda3/include/qt/QtCore/qatomic.h \
		../anaconda3/include/qt/QtCore/qbasicatomic.h \
		../anaconda3/include/qt/QtCore/qatomic_bootstrap.h \
		../anaconda3/include/qt/QtCore/qgenericatomic.h \
		../anaconda3/include/qt/QtCore/qatomic_cxx11.h \
		../anaconda3/include/qt/QtCore/qatomic_msvc.h \
		../anaconda3/include/qt/QtCore/qglobalstatic.h \
		../anaconda3/include/qt/QtCore/qmutex.h \
		../anaconda3/include/qt/QtCore/qnumeric.h \
		../anaconda3/include/qt/QtCore/qversiontagging.h \
		../anaconda3/include/qt/QtGui/qtgui-config.h \
		../anaconda3/include/qt/QtWidgets/qtwidgets-config.h \
		../anaconda3/include/qt/QtCore/qobject.h \
		../anaconda3/include/qt/QtCore/qobjectdefs.h \
		../anaconda3/include/qt/QtCore/qnamespace.h \
		../anaconda3/include/qt/QtCore/qobjectdefs_impl.h \
		../anaconda3/include/qt/QtCore/qstring.h \
		../anaconda3/include/qt/QtCore/qchar.h \
		../anaconda3/include/qt/QtCore/qbytearray.h \
		../anaconda3/include/qt/QtCore/qrefcount.h \
		../anaconda3/include/qt/QtCore/qarraydata.h \
		../anaconda3/include/qt/QtCore/qstringbuilder.h \
		../anaconda3/include/qt/QtCore/qlist.h \
		../anaconda3/include/qt/QtCore/qalgorithms.h \
		../anaconda3/include/qt/QtCore/qiterator.h \
		../anaconda3/include/qt/QtCore/qhashfunctions.h \
		../anaconda3/include/qt/QtCore/qpair.h \
		../anaconda3/include/qt/QtCore/qbytearraylist.h \
		../anaconda3/include/qt/QtCore/qstringlist.h \
		../anaconda3/include/qt/QtCore/qregexp.h \
		../anaconda3/include/qt/QtCore/qstringmatcher.h \
		../anaconda3/include/qt/QtCore/qcoreevent.h \
		../anaconda3/include/qt/QtCore/qscopedpointer.h \
		../anaconda3/include/qt/QtCore/qmetatype.h \
		../anaconda3/include/qt/QtCore/qvarlengtharray.h \
		../anaconda3/include/qt/QtCore/qcontainerfwd.h \
		../anaconda3/include/qt/QtCore/qobject_impl.h \
		../anaconda3/include/qt/QtCore/qvariant.h \
		../anaconda3/include/qt/QtCore/qmap.h \
		../anaconda3/include/qt/QtCore/qdebug.h \
		../anaconda3/include/qt/QtCore/qhash.h \
		../anaconda3/include/qt/QtCore/qtextstream.h \
		../anaconda3/include/qt/QtCore/qiodevice.h \
		../anaconda3/include/qt/QtCore/qlocale.h \
		../anaconda3/include/qt/QtCore/qshareddata.h \
		../anaconda3/include/qt/QtCore/qvector.h \
		../anaconda3/include/qt/QtCore/qpoint.h \
		../anaconda3/include/qt/QtCore/qset.h \
		../anaconda3/include/qt/QtCore/qcontiguouscache.h \
		../anaconda3/include/qt/QtCore/qsharedpointer.h \
		../anaconda3/include/qt/QtCore/qsharedpointer_impl.h \
		../anaconda3/include/qt/QtCore/qrect.h \
		../anaconda3/include/qt/QtCore/qmargins.h \
		../anaconda3/include/qt/QtCore/qsize.h \
		../anaconda3/include/qt/QtGui/qpainterpath.h \
		../anaconda3/include/qt/QtGui/qmatrix.h \
		../anaconda3/include/qt/QtGui/qpolygon.h \
		../anaconda3/include/qt/QtGui/qregion.h \
		../anaconda3/include/qt/QtGui/qwindowdefs.h \
		../anaconda3/include/qt/QtGui/qwindowdefs_win.h \
		../anaconda3/include/qt/QtCore/qdatastream.h \
		../anaconda3/include/qt/QtCore/qline.h \
		../anaconda3/include/qt/QtGui/qpixmap.h \
		../anaconda3/include/qt/QtGui/qpaintdevice.h \
		../anaconda3/include/qt/QtGui/qcolor.h \
		../anaconda3/include/qt/QtGui/qrgb.h \
		../anaconda3/include/qt/QtGui/qrgba64.h \
		../anaconda3/include/qt/QtGui/qimage.h \
		../anaconda3/include/qt/QtGui/qpixelformat.h \
		../anaconda3/include/qt/QtGui/qtransform.h \
		../anaconda3/include/qt/QtWidgets/QGraphicsItem \
		../anaconda3/include/qt/QtCore/QObject
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o car_graphic.o Bypass_GUI/car_graphic.cpp

main.o: Bypass_GUI/main.cpp ../anaconda3/include/qt/QtWidgets/QApplication \
		../anaconda3/include/qt/QtWidgets/qapplication.h \
		../anaconda3/include/qt/QtWidgets/qtwidgetsglobal.h \
		../anaconda3/include/qt/QtGui/qtguiglobal.h \
		../anaconda3/include/qt/QtCore/qglobal.h \
		../anaconda3/include/qt/QtCore/qconfig-bootstrapped.h \
		../anaconda3/include/qt/QtCore/qconfig.h \
		../anaconda3/include/qt/QtCore/qtcore-config.h \
		../anaconda3/include/qt/QtCore/qsystemdetection.h \
		../anaconda3/include/qt/QtCore/qprocessordetection.h \
		../anaconda3/include/qt/QtCore/qcompilerdetection.h \
		../anaconda3/include/qt/QtCore/qtypeinfo.h \
		../anaconda3/include/qt/QtCore/qsysinfo.h \
		../anaconda3/include/qt/QtCore/qlogging.h \
		../anaconda3/include/qt/QtCore/qflags.h \
		../anaconda3/include/qt/QtCore/qatomic.h \
		../anaconda3/include/qt/QtCore/qbasicatomic.h \
		../anaconda3/include/qt/QtCore/qatomic_bootstrap.h \
		../anaconda3/include/qt/QtCore/qgenericatomic.h \
		../anaconda3/include/qt/QtCore/qatomic_cxx11.h \
		../anaconda3/include/qt/QtCore/qatomic_msvc.h \
		../anaconda3/include/qt/QtCore/qglobalstatic.h \
		../anaconda3/include/qt/QtCore/qmutex.h \
		../anaconda3/include/qt/QtCore/qnumeric.h \
		../anaconda3/include/qt/QtCore/qversiontagging.h \
		../anaconda3/include/qt/QtGui/qtgui-config.h \
		../anaconda3/include/qt/QtWidgets/qtwidgets-config.h \
		../anaconda3/include/qt/QtCore/qcoreapplication.h \
		../anaconda3/include/qt/QtCore/qstring.h \
		../anaconda3/include/qt/QtCore/qchar.h \
		../anaconda3/include/qt/QtCore/qbytearray.h \
		../anaconda3/include/qt/QtCore/qrefcount.h \
		../anaconda3/include/qt/QtCore/qnamespace.h \
		../anaconda3/include/qt/QtCore/qarraydata.h \
		../anaconda3/include/qt/QtCore/qstringbuilder.h \
		../anaconda3/include/qt/QtCore/qobject.h \
		../anaconda3/include/qt/QtCore/qobjectdefs.h \
		../anaconda3/include/qt/QtCore/qobjectdefs_impl.h \
		../anaconda3/include/qt/QtCore/qlist.h \
		../anaconda3/include/qt/QtCore/qalgorithms.h \
		../anaconda3/include/qt/QtCore/qiterator.h \
		../anaconda3/include/qt/QtCore/qhashfunctions.h \
		../anaconda3/include/qt/QtCore/qpair.h \
		../anaconda3/include/qt/QtCore/qbytearraylist.h \
		../anaconda3/include/qt/QtCore/qstringlist.h \
		../anaconda3/include/qt/QtCore/qregexp.h \
		../anaconda3/include/qt/QtCore/qstringmatcher.h \
		../anaconda3/include/qt/QtCore/qcoreevent.h \
		../anaconda3/include/qt/QtCore/qscopedpointer.h \
		../anaconda3/include/qt/QtCore/qmetatype.h \
		../anaconda3/include/qt/QtCore/qvarlengtharray.h \
		../anaconda3/include/qt/QtCore/qcontainerfwd.h \
		../anaconda3/include/qt/QtCore/qobject_impl.h \
		../anaconda3/include/qt/QtCore/qeventloop.h \
		../anaconda3/include/qt/QtGui/qwindowdefs.h \
		../anaconda3/include/qt/QtGui/qwindowdefs_win.h \
		../anaconda3/include/qt/QtCore/qpoint.h \
		../anaconda3/include/qt/QtCore/qsize.h \
		../anaconda3/include/qt/QtGui/qcursor.h \
		../anaconda3/include/qt/QtWidgets/qdesktopwidget.h \
		../anaconda3/include/qt/QtWidgets/qwidget.h \
		../anaconda3/include/qt/QtCore/qmargins.h \
		../anaconda3/include/qt/QtGui/qpaintdevice.h \
		../anaconda3/include/qt/QtCore/qrect.h \
		../anaconda3/include/qt/QtGui/qpalette.h \
		../anaconda3/include/qt/QtGui/qcolor.h \
		../anaconda3/include/qt/QtGui/qrgb.h \
		../anaconda3/include/qt/QtGui/qrgba64.h \
		../anaconda3/include/qt/QtGui/qbrush.h \
		../anaconda3/include/qt/QtCore/qvector.h \
		../anaconda3/include/qt/QtGui/qmatrix.h \
		../anaconda3/include/qt/QtGui/qpolygon.h \
		../anaconda3/include/qt/QtGui/qregion.h \
		../anaconda3/include/qt/QtCore/qdatastream.h \
		../anaconda3/include/qt/QtCore/qiodevice.h \
		../anaconda3/include/qt/QtCore/qline.h \
		../anaconda3/include/qt/QtGui/qtransform.h \
		../anaconda3/include/qt/QtGui/qpainterpath.h \
		../anaconda3/include/qt/QtGui/qimage.h \
		../anaconda3/include/qt/QtGui/qpixelformat.h \
		../anaconda3/include/qt/QtGui/qpixmap.h \
		../anaconda3/include/qt/QtCore/qsharedpointer.h \
		../anaconda3/include/qt/QtCore/qshareddata.h \
		../anaconda3/include/qt/QtCore/qhash.h \
		../anaconda3/include/qt/QtCore/qsharedpointer_impl.h \
		../anaconda3/include/qt/QtGui/qfont.h \
		../anaconda3/include/qt/QtGui/qfontmetrics.h \
		../anaconda3/include/qt/QtGui/qfontinfo.h \
		../anaconda3/include/qt/QtWidgets/qsizepolicy.h \
		../anaconda3/include/qt/QtGui/qkeysequence.h \
		../anaconda3/include/qt/QtGui/qevent.h \
		../anaconda3/include/qt/QtCore/qvariant.h \
		../anaconda3/include/qt/QtCore/qmap.h \
		../anaconda3/include/qt/QtCore/qdebug.h \
		../anaconda3/include/qt/QtCore/qtextstream.h \
		../anaconda3/include/qt/QtCore/qlocale.h \
		../anaconda3/include/qt/QtCore/qset.h \
		../anaconda3/include/qt/QtCore/qcontiguouscache.h \
		../anaconda3/include/qt/QtCore/qurl.h \
		../anaconda3/include/qt/QtCore/qurlquery.h \
		../anaconda3/include/qt/QtCore/qfile.h \
		../anaconda3/include/qt/QtCore/qfiledevice.h \
		../anaconda3/include/qt/QtGui/qvector2d.h \
		../anaconda3/include/qt/QtGui/qtouchdevice.h \
		../anaconda3/include/qt/QtGui/qguiapplication.h \
		../anaconda3/include/qt/QtGui/qinputmethod.h \
		../anaconda3/include/qt/QtWidgets/QLabel \
		../anaconda3/include/qt/QtWidgets/qlabel.h \
		../anaconda3/include/qt/QtWidgets/qframe.h \
		../anaconda3/include/qt/QtWidgets/QGraphicsScene \
		../anaconda3/include/qt/QtWidgets/qgraphicsscene.h \
		../anaconda3/include/qt/QtGui/qpen.h \
		../anaconda3/include/qt/QtWidgets/QGraphicsRectItem \
		../anaconda3/include/qt/QtWidgets/qgraphicsitem.h \
		Bypass_GUI/simulation_gui.hpp \
		../anaconda3/include/qt/QtWidgets/QGraphicsView \
		../anaconda3/include/qt/QtWidgets/qgraphicsview.h \
		../anaconda3/include/qt/QtGui/qpainter.h \
		../anaconda3/include/qt/QtGui/qtextoption.h \
		../anaconda3/include/qt/QtWidgets/qscrollarea.h \
		../anaconda3/include/qt/QtWidgets/qabstractscrollarea.h \
		../anaconda3/include/qt/QtWidgets/QGraphicsPixmapItem \
		../anaconda3/include/qt/QtWidgets/QGraphicsItem \
		../anaconda3/include/qt/QtCore/QObject \
		../anaconda3/include/qt/QtWidgets/QPushButton \
		../anaconda3/include/qt/QtWidgets/qpushbutton.h \
		../anaconda3/include/qt/QtWidgets/qabstractbutton.h \
		../anaconda3/include/qt/QtGui/qicon.h \
		../anaconda3/include/qt/QtWidgets/QGridLayout \
		../anaconda3/include/qt/QtWidgets/qgridlayout.h \
		../anaconda3/include/qt/QtWidgets/qlayout.h \
		../anaconda3/include/qt/QtWidgets/qlayoutitem.h \
		../anaconda3/include/qt/QtWidgets/qboxlayout.h \
		../anaconda3/include/qt/QtWidgets/QTextEdit \
		../anaconda3/include/qt/QtWidgets/qtextedit.h \
		../anaconda3/include/qt/QtGui/qtextdocument.h \
		../anaconda3/include/qt/QtGui/qtextcursor.h \
		../anaconda3/include/qt/QtGui/qtextformat.h \
		../anaconda3/include/qt/QtWidgets/QSlider \
		../anaconda3/include/qt/QtWidgets/qslider.h \
		../anaconda3/include/qt/QtWidgets/qabstractslider.h \
		Bypass_GUI/car_graphic.hpp \
		bypass/Simulation.hpp \
		bypass/Bypass.hpp \
		bypass/BypassSection.hpp \
		bypass/Vehicle.hpp \
		bypass/Road.hpp \
		bypass/Junction.hpp \
		../anaconda3/include/qt/QtCore/QTimer \
		../anaconda3/include/qt/QtCore/qtimer.h \
		../anaconda3/include/qt/QtCore/qbasictimer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o Bypass_GUI/main.cpp

simulation_gui.o: Bypass_GUI/simulation_gui.cpp Bypass_GUI/simulation_gui.hpp \
		../anaconda3/include/qt/QtWidgets/QGraphicsView \
		../anaconda3/include/qt/QtWidgets/qgraphicsview.h \
		../anaconda3/include/qt/QtWidgets/qtwidgetsglobal.h \
		../anaconda3/include/qt/QtGui/qtguiglobal.h \
		../anaconda3/include/qt/QtCore/qglobal.h \
		../anaconda3/include/qt/QtCore/qconfig-bootstrapped.h \
		../anaconda3/include/qt/QtCore/qconfig.h \
		../anaconda3/include/qt/QtCore/qtcore-config.h \
		../anaconda3/include/qt/QtCore/qsystemdetection.h \
		../anaconda3/include/qt/QtCore/qprocessordetection.h \
		../anaconda3/include/qt/QtCore/qcompilerdetection.h \
		../anaconda3/include/qt/QtCore/qtypeinfo.h \
		../anaconda3/include/qt/QtCore/qsysinfo.h \
		../anaconda3/include/qt/QtCore/qlogging.h \
		../anaconda3/include/qt/QtCore/qflags.h \
		../anaconda3/include/qt/QtCore/qatomic.h \
		../anaconda3/include/qt/QtCore/qbasicatomic.h \
		../anaconda3/include/qt/QtCore/qatomic_bootstrap.h \
		../anaconda3/include/qt/QtCore/qgenericatomic.h \
		../anaconda3/include/qt/QtCore/qatomic_cxx11.h \
		../anaconda3/include/qt/QtCore/qatomic_msvc.h \
		../anaconda3/include/qt/QtCore/qglobalstatic.h \
		../anaconda3/include/qt/QtCore/qmutex.h \
		../anaconda3/include/qt/QtCore/qnumeric.h \
		../anaconda3/include/qt/QtCore/qversiontagging.h \
		../anaconda3/include/qt/QtGui/qtgui-config.h \
		../anaconda3/include/qt/QtWidgets/qtwidgets-config.h \
		../anaconda3/include/qt/QtCore/qmetatype.h \
		../anaconda3/include/qt/QtCore/qbytearray.h \
		../anaconda3/include/qt/QtCore/qrefcount.h \
		../anaconda3/include/qt/QtCore/qnamespace.h \
		../anaconda3/include/qt/QtCore/qarraydata.h \
		../anaconda3/include/qt/QtCore/qstring.h \
		../anaconda3/include/qt/QtCore/qchar.h \
		../anaconda3/include/qt/QtCore/qstringbuilder.h \
		../anaconda3/include/qt/QtCore/qvarlengtharray.h \
		../anaconda3/include/qt/QtCore/qcontainerfwd.h \
		../anaconda3/include/qt/QtCore/qalgorithms.h \
		../anaconda3/include/qt/QtCore/qobjectdefs.h \
		../anaconda3/include/qt/QtCore/qobjectdefs_impl.h \
		../anaconda3/include/qt/QtGui/qpainter.h \
		../anaconda3/include/qt/QtCore/qrect.h \
		../anaconda3/include/qt/QtCore/qmargins.h \
		../anaconda3/include/qt/QtCore/qsize.h \
		../anaconda3/include/qt/QtCore/qpoint.h \
		../anaconda3/include/qt/QtCore/qscopedpointer.h \
		../anaconda3/include/qt/QtGui/qpixmap.h \
		../anaconda3/include/qt/QtGui/qpaintdevice.h \
		../anaconda3/include/qt/QtGui/qwindowdefs.h \
		../anaconda3/include/qt/QtGui/qwindowdefs_win.h \
		../anaconda3/include/qt/QtGui/qcolor.h \
		../anaconda3/include/qt/QtGui/qrgb.h \
		../anaconda3/include/qt/QtCore/qstringlist.h \
		../anaconda3/include/qt/QtCore/qlist.h \
		../anaconda3/include/qt/QtCore/qiterator.h \
		../anaconda3/include/qt/QtCore/qhashfunctions.h \
		../anaconda3/include/qt/QtCore/qpair.h \
		../anaconda3/include/qt/QtCore/qbytearraylist.h \
		../anaconda3/include/qt/QtCore/qregexp.h \
		../anaconda3/include/qt/QtCore/qstringmatcher.h \
		../anaconda3/include/qt/QtGui/qrgba64.h \
		../anaconda3/include/qt/QtCore/qsharedpointer.h \
		../anaconda3/include/qt/QtCore/qshareddata.h \
		../anaconda3/include/qt/QtCore/qhash.h \
		../anaconda3/include/qt/QtCore/qsharedpointer_impl.h \
		../anaconda3/include/qt/QtCore/qobject.h \
		../anaconda3/include/qt/QtCore/qcoreevent.h \
		../anaconda3/include/qt/QtCore/qobject_impl.h \
		../anaconda3/include/qt/QtGui/qimage.h \
		../anaconda3/include/qt/QtGui/qpixelformat.h \
		../anaconda3/include/qt/QtGui/qtransform.h \
		../anaconda3/include/qt/QtGui/qmatrix.h \
		../anaconda3/include/qt/QtGui/qpolygon.h \
		../anaconda3/include/qt/QtCore/qvector.h \
		../anaconda3/include/qt/QtGui/qregion.h \
		../anaconda3/include/qt/QtCore/qdatastream.h \
		../anaconda3/include/qt/QtCore/qiodevice.h \
		../anaconda3/include/qt/QtCore/qline.h \
		../anaconda3/include/qt/QtGui/qpainterpath.h \
		../anaconda3/include/qt/QtGui/qtextoption.h \
		../anaconda3/include/qt/QtGui/qpen.h \
		../anaconda3/include/qt/QtGui/qbrush.h \
		../anaconda3/include/qt/QtGui/qfontinfo.h \
		../anaconda3/include/qt/QtGui/qfont.h \
		../anaconda3/include/qt/QtGui/qfontmetrics.h \
		../anaconda3/include/qt/QtWidgets/qscrollarea.h \
		../anaconda3/include/qt/QtWidgets/qabstractscrollarea.h \
		../anaconda3/include/qt/QtWidgets/qframe.h \
		../anaconda3/include/qt/QtWidgets/qwidget.h \
		../anaconda3/include/qt/QtGui/qpalette.h \
		../anaconda3/include/qt/QtWidgets/qsizepolicy.h \
		../anaconda3/include/qt/QtGui/qcursor.h \
		../anaconda3/include/qt/QtGui/qkeysequence.h \
		../anaconda3/include/qt/QtGui/qevent.h \
		../anaconda3/include/qt/QtCore/qvariant.h \
		../anaconda3/include/qt/QtCore/qmap.h \
		../anaconda3/include/qt/QtCore/qdebug.h \
		../anaconda3/include/qt/QtCore/qtextstream.h \
		../anaconda3/include/qt/QtCore/qlocale.h \
		../anaconda3/include/qt/QtCore/qset.h \
		../anaconda3/include/qt/QtCore/qcontiguouscache.h \
		../anaconda3/include/qt/QtCore/qurl.h \
		../anaconda3/include/qt/QtCore/qurlquery.h \
		../anaconda3/include/qt/QtCore/qfile.h \
		../anaconda3/include/qt/QtCore/qfiledevice.h \
		../anaconda3/include/qt/QtGui/qvector2d.h \
		../anaconda3/include/qt/QtGui/qtouchdevice.h \
		../anaconda3/include/qt/QtWidgets/qgraphicsscene.h \
		../anaconda3/include/qt/QtWidgets/QGraphicsPixmapItem \
		../anaconda3/include/qt/QtWidgets/qgraphicsitem.h \
		../anaconda3/include/qt/QtWidgets/QGraphicsItem \
		../anaconda3/include/qt/QtCore/QObject \
		../anaconda3/include/qt/QtWidgets/QGraphicsScene \
		../anaconda3/include/qt/QtWidgets/QPushButton \
		../anaconda3/include/qt/QtWidgets/qpushbutton.h \
		../anaconda3/include/qt/QtWidgets/qabstractbutton.h \
		../anaconda3/include/qt/QtGui/qicon.h \
		../anaconda3/include/qt/QtWidgets/QGridLayout \
		../anaconda3/include/qt/QtWidgets/qgridlayout.h \
		../anaconda3/include/qt/QtWidgets/qlayout.h \
		../anaconda3/include/qt/QtWidgets/qlayoutitem.h \
		../anaconda3/include/qt/QtWidgets/qboxlayout.h \
		../anaconda3/include/qt/QtWidgets/QTextEdit \
		../anaconda3/include/qt/QtWidgets/qtextedit.h \
		../anaconda3/include/qt/QtGui/qtextdocument.h \
		../anaconda3/include/qt/QtGui/qtextcursor.h \
		../anaconda3/include/qt/QtGui/qtextformat.h \
		../anaconda3/include/qt/QtWidgets/QSlider \
		../anaconda3/include/qt/QtWidgets/qslider.h \
		../anaconda3/include/qt/QtWidgets/qabstractslider.h \
		Bypass_GUI/car_graphic.hpp \
		bypass/Simulation.hpp \
		bypass/Bypass.hpp \
		bypass/BypassSection.hpp \
		bypass/Vehicle.hpp \
		bypass/Road.hpp \
		bypass/Junction.hpp \
		../anaconda3/include/qt/QtCore/QTimer \
		../anaconda3/include/qt/QtCore/qtimer.h \
		../anaconda3/include/qt/QtCore/qbasictimer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o simulation_gui.o Bypass_GUI/simulation_gui.cpp

vehicle.o: bypass/vehicle.cpp bypass/Vehicle.hpp \
		../anaconda3/include/qt/QtWidgets/QGraphicsPixmapItem \
		../anaconda3/include/qt/QtWidgets/qgraphicsitem.h \
		../anaconda3/include/qt/QtWidgets/qtwidgetsglobal.h \
		../anaconda3/include/qt/QtGui/qtguiglobal.h \
		../anaconda3/include/qt/QtCore/qglobal.h \
		../anaconda3/include/qt/QtCore/qconfig-bootstrapped.h \
		../anaconda3/include/qt/QtCore/qconfig.h \
		../anaconda3/include/qt/QtCore/qtcore-config.h \
		../anaconda3/include/qt/QtCore/qsystemdetection.h \
		../anaconda3/include/qt/QtCore/qprocessordetection.h \
		../anaconda3/include/qt/QtCore/qcompilerdetection.h \
		../anaconda3/include/qt/QtCore/qtypeinfo.h \
		../anaconda3/include/qt/QtCore/qsysinfo.h \
		../anaconda3/include/qt/QtCore/qlogging.h \
		../anaconda3/include/qt/QtCore/qflags.h \
		../anaconda3/include/qt/QtCore/qatomic.h \
		../anaconda3/include/qt/QtCore/qbasicatomic.h \
		../anaconda3/include/qt/QtCore/qatomic_bootstrap.h \
		../anaconda3/include/qt/QtCore/qgenericatomic.h \
		../anaconda3/include/qt/QtCore/qatomic_cxx11.h \
		../anaconda3/include/qt/QtCore/qatomic_msvc.h \
		../anaconda3/include/qt/QtCore/qglobalstatic.h \
		../anaconda3/include/qt/QtCore/qmutex.h \
		../anaconda3/include/qt/QtCore/qnumeric.h \
		../anaconda3/include/qt/QtCore/qversiontagging.h \
		../anaconda3/include/qt/QtGui/qtgui-config.h \
		../anaconda3/include/qt/QtWidgets/qtwidgets-config.h \
		../anaconda3/include/qt/QtCore/qobject.h \
		../anaconda3/include/qt/QtCore/qobjectdefs.h \
		../anaconda3/include/qt/QtCore/qnamespace.h \
		../anaconda3/include/qt/QtCore/qobjectdefs_impl.h \
		../anaconda3/include/qt/QtCore/qstring.h \
		../anaconda3/include/qt/QtCore/qchar.h \
		../anaconda3/include/qt/QtCore/qbytearray.h \
		../anaconda3/include/qt/QtCore/qrefcount.h \
		../anaconda3/include/qt/QtCore/qarraydata.h \
		../anaconda3/include/qt/QtCore/qstringbuilder.h \
		../anaconda3/include/qt/QtCore/qlist.h \
		../anaconda3/include/qt/QtCore/qalgorithms.h \
		../anaconda3/include/qt/QtCore/qiterator.h \
		../anaconda3/include/qt/QtCore/qhashfunctions.h \
		../anaconda3/include/qt/QtCore/qpair.h \
		../anaconda3/include/qt/QtCore/qbytearraylist.h \
		../anaconda3/include/qt/QtCore/qstringlist.h \
		../anaconda3/include/qt/QtCore/qregexp.h \
		../anaconda3/include/qt/QtCore/qstringmatcher.h \
		../anaconda3/include/qt/QtCore/qcoreevent.h \
		../anaconda3/include/qt/QtCore/qscopedpointer.h \
		../anaconda3/include/qt/QtCore/qmetatype.h \
		../anaconda3/include/qt/QtCore/qvarlengtharray.h \
		../anaconda3/include/qt/QtCore/qcontainerfwd.h \
		../anaconda3/include/qt/QtCore/qobject_impl.h \
		../anaconda3/include/qt/QtCore/qvariant.h \
		../anaconda3/include/qt/QtCore/qmap.h \
		../anaconda3/include/qt/QtCore/qdebug.h \
		../anaconda3/include/qt/QtCore/qhash.h \
		../anaconda3/include/qt/QtCore/qtextstream.h \
		../anaconda3/include/qt/QtCore/qiodevice.h \
		../anaconda3/include/qt/QtCore/qlocale.h \
		../anaconda3/include/qt/QtCore/qshareddata.h \
		../anaconda3/include/qt/QtCore/qvector.h \
		../anaconda3/include/qt/QtCore/qpoint.h \
		../anaconda3/include/qt/QtCore/qset.h \
		../anaconda3/include/qt/QtCore/qcontiguouscache.h \
		../anaconda3/include/qt/QtCore/qsharedpointer.h \
		../anaconda3/include/qt/QtCore/qsharedpointer_impl.h \
		../anaconda3/include/qt/QtCore/qrect.h \
		../anaconda3/include/qt/QtCore/qmargins.h \
		../anaconda3/include/qt/QtCore/qsize.h \
		../anaconda3/include/qt/QtGui/qpainterpath.h \
		../anaconda3/include/qt/QtGui/qmatrix.h \
		../anaconda3/include/qt/QtGui/qpolygon.h \
		../anaconda3/include/qt/QtGui/qregion.h \
		../anaconda3/include/qt/QtGui/qwindowdefs.h \
		../anaconda3/include/qt/QtGui/qwindowdefs_win.h \
		../anaconda3/include/qt/QtCore/qdatastream.h \
		../anaconda3/include/qt/QtCore/qline.h \
		../anaconda3/include/qt/QtGui/qpixmap.h \
		../anaconda3/include/qt/QtGui/qpaintdevice.h \
		../anaconda3/include/qt/QtGui/qcolor.h \
		../anaconda3/include/qt/QtGui/qrgb.h \
		../anaconda3/include/qt/QtGui/qrgba64.h \
		../anaconda3/include/qt/QtGui/qimage.h \
		../anaconda3/include/qt/QtGui/qpixelformat.h \
		../anaconda3/include/qt/QtGui/qtransform.h \
		../anaconda3/include/qt/QtWidgets/QGraphicsItem \
		../anaconda3/include/qt/QtCore/QObject \
		../anaconda3/include/qt/QtCore/QDebug
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o vehicle.o bypass/vehicle.cpp

qrc_res.o: qrc_res.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_res.o qrc_res.cpp

moc_car_graphic.o: moc_car_graphic.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_car_graphic.o moc_car_graphic.cpp

moc_simulation_gui.o: moc_simulation_gui.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_simulation_gui.o moc_simulation_gui.cpp

moc_Vehicle.o: moc_Vehicle.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Vehicle.o moc_Vehicle.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/Simulation_of_the_4th_Krakow_bypass/bin || mkdir -p $(INSTALL_ROOT)/opt/Simulation_of_the_4th_Krakow_bypass/bin
	-$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/Simulation_of_the_4th_Krakow_bypass/bin/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/opt/Simulation_of_the_4th_Krakow_bypass/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/Simulation_of_the_4th_Krakow_bypass/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/Simulation_of_the_4th_Krakow_bypass/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

