//
// Created by mazi on 18.04.19.
//

#ifndef SIMULATION_OF_THE_4TH_KRAKOW_BYPASS_BASIC_CHECK_HPP
#define SIMULATION_OF_THE_4TH_KRAKOW_BYPASS_BASIC_CHECK_HPP

void runbasictest();

#endif //SIMULATION_OF_THE_4TH_KRAKOW_BYPASS_BASIC_CHECK_HPP
