//
// Created by mazi on 19.04.19.
//

#ifndef SIMULATION_OF_THE_4TH_KRAKOW_BYPASS_BYPASS_HPP
#define SIMULATION_OF_THE_4TH_KRAKOW_BYPASS_BYPASS_HPP


class Bypass {

};


#endif //SIMULATION_OF_THE_4TH_KRAKOW_BYPASS_BYPASS_HPP
